src/main/java/Beans/CategoryBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beans;

import POJO.Category;
import POJO.TestStep;
import POJO.TestStep_Category;
import Services.CategoryService;
import Services.QuestionService;
import Services.AnswerService;
import Services.TestStep_CategoryService;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.event.ActionEvent;

/**
 *
 * @author Lisa
 */
public class CategoryBean implements Serializable{

    private NavigationBean navi;
    private CategoryService catS = CategoryService.getInstance();
    private QuestionService quS = QuestionService.getInstance();
    private AnswerService aService = AnswerService.getInstance();
    private List<Category> categoriesOfTestStep=new ArrayList<>();
    private List<TestStep_Category> t_cList=new ArrayList<>();
    private TestStep_CategoryService t_cService = TestStep_CategoryService.getInstance();
    private TestStepBean stepBean;

     public void home(ActionEvent event){
        navi.setTest(null);
        navi.setTestStep(null);
        navi.setCategory(null);
    }     

    public NavigationBean getNavi() {
        return navi;
    }

    public void setNavi(NavigationBean navi) {
        this.navi = navi;
    }

    public TestStepBean getStepBean() {
        return stepBean;
    }

    public void setStepBean(TestStepBean stepBean) {
        this.stepBean = stepBean;
    }

    public CategoryService getCatS() {
        return catS;
    }

    public void setCatS(CategoryService catS) {
        this.catS = catS;
    }

    public QuestionService getQuS() {
        return quS;
    }

    public void setQuS(QuestionService quS) {
        this.quS = quS;
    }

    public AnswerService getaService() {
        return aService;
    }

    public void setaService(AnswerService aService) {
        this.aService = aService;
    }
    
    public void saveNavigation(Category cat){
        navi.setCategory(cat);
    }
    public List<Category> getCategoriesOfTestStep() {
        TestStep teststep = navi.getTestStep();
        categoriesOfTestStep.clear();

        if (teststep != null) {
            t_cList.clear();

            for (TestStep_Category tc : t_cService.getList()) {
                if (tc.getTestStepID() == teststep.getId()) {
                    for (Category c : catS.getList()) {
                        if (c.getId() == tc.getCategoryID()) {
                            categoriesOfTestStep.add(c);
                        }
                    }
                }

            }           
        }
        return categoriesOfTestStep;
    }
    public List<Category> getCategoriesPerTestStep(TestStep teststep) {       
        TestStep oldStep=navi.getTestStep();
        navi.setTestStep(teststep);
        categoriesOfTestStep=getCategoriesOfTestStep();
        navi.setTestStep(oldStep);
        return categoriesOfTestStep;
    }
    public List<Category> getCategoriesOfTest() {
        List<Category> catsPerTest=new ArrayList<>();
        if(navi.getTest()!=null){
            TestStep actualStep = navi.getTestStep();
            List<TestStep> stepList =stepBean.getTestStepsOfTest();
            for(TestStep step:stepList){
                navi.setTestStep(step);
                List<Category> catsPerStep=getCategoriesPerTestStep(step);
                for(Category c: catsPerStep){
                    if(!catsPerTest.contains(c)){
                        catsPerTest.add(c);
                    }
                }
            }
            navi.setTestStep(actualStep);
        }
        return catsPerTest;
    }
}

src/main/java/Beans/FileDownloadBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Beans;

import java.io.InputStream;
import java.io.Serializable;
import javax.faces.context.FacesContext;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

/**
 *
 * @author Denise
 */
public class FileDownloadBean implements Serializable{

    private StreamedContent file;
    private NavigationBean navi;

    public NavigationBean getNavi() {
        return navi;
    }

    public void setNavi(NavigationBean navi) {
        this.navi = navi;
    }
 
    public StreamedContent getHelpFile() {
        InputStream stream = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/help/Helpbook.pdf");
        file = new DefaultStreamedContent(stream, "application/pdf", "Hilfe.pdf");
        return file;
    }
    public StreamedContent getAdminHelp() {
        InputStream stream = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/help/Adminhelp.pdf");
        file = new DefaultStreamedContent(stream, "application/pdf", "Administratorhandbuch.pdf");
        return file;
    }
    
    public StreamedContent getSuperuserHelp() {
        InputStream stream = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/help/Superuserhelp.pdf");
        file = new DefaultStreamedContent(stream, "application/pdf", "Superuserhandbuch.pdf");
        return file;
    }
    
    public StreamedContent getInstructionFile() {
        InputStream stream = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/help/ImportAnleitung.pdf");
        file = new DefaultStreamedContent(stream, "application/pdf", "ImportAnleitung.pdf");
        return file;
    }
    public StreamedContent getLearningDoc() {
        String fileName=navi.getTestStep().getName();
        InputStream stream = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/Lernunterlagen/"+fileName+".pdf");
        file = new DefaultStreamedContent(stream, "application/pdf", fileName+".pdf");
        return file;
    }
    public StreamedContent getCSVTemplate() {
        InputStream stream = FacesContext.getCurrentInstance().getExternalContext().getResourceAsStream("/resources/templates/FragenImportieren.csv");
        file = new DefaultStreamedContent(stream, "text/csv", "FragenImportieren.csv");
        return file;
    }
}

src/main/java/Beans/QuestionBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beans;

import Cookie.CookieHelper;
import POJO.Answer;
import POJO.Category;
import POJO.Question;
import POJO.TestStep;
import POJO.TestStep_Question;
import Services.AnswerService;
import Services.FirebrigadeService;
import Services.QuestionService;
import Services.TestStep_QuestionService;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.faces.component.UIComponent;
import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.servlet.http.Cookie;
import javax.servlet.http.HttpSession;
import jersey.repackaged.com.google.common.base.Objects;
import jersey.repackaged.com.google.common.collect.Maps;
import org.apache.commons.lang.StringUtils;

public class QuestionBean implements Serializable{

    private NavigationBean navi;
    private int questionCnt = 0;
    private QuestionService questionService = QuestionService.getInstance();
    private Category category;
    private Question question;
    private AnswerService answerService = AnswerService.getInstance();
    private boolean isMultCh = false;
    private boolean isText = false;
    private boolean isNumbering = false;
    private boolean isPicSelection = false;
    private boolean isComparison = false;
    private boolean isVideo = false;
    private List<String> selectedAnswers = new ArrayList<>();
    private List<Answer> answerList;
    private String action = "/questions.xhtml";
    private int questionsPerCat = 0;
    private Map<Integer, String> inputMap = new HashMap<>();
    private String hint = "";
    private int trueAnswers = 0;
    private int cnt = 1;
    private Map<Integer, Boolean> boolMap = new HashMap<>();
    private String correct = "";
    private Map<Integer, Integer> numMap = new HashMap<>();
    private Map<Integer, Answer> answerCache = Maps.newHashMap();
    private boolean isSolutionRequired = false;
    private boolean rightAnswersShouldBeShown = false;
    private int columnCnt = 0;
    private String username = "";
    private CookieHelper cookieHelper = new CookieHelper();
    private int kindOfTest = 5;//1=Fragen üben, 2=Falsch beatwortete Fragen üben
    private List<Question> qList = new ArrayList<>();
    private LoginBean loginBean;
    private FirebrigadeService fbService = FirebrigadeService.getInstance();
    private final String COMMANDER = "commander", FOUNDINGYEAR = "foundingYear", YOUTHCOMMANDER = "youthCommander", RESCUEEQUIPMENT = "rescueEquipment", SECTION = "section";
    private String categoryNameWithArrow;
    private List<Question> questionsOfCategoryPerTestStep=new ArrayList<>();
    private List<TestStep_Question> t_qList=new ArrayList<>();
    private List<Question> questionsPerTestStep=new ArrayList<>();
    private TestStep_QuestionService t_qService=TestStep_QuestionService.getInstance();

    @PostConstruct
    public void init(){
        category = navi.getCategory();
    }
    public NavigationBean getNavi() {
        return navi;
    }

    public void setNavi(NavigationBean navi) {
        this.navi = navi;
    }
    
    public LoginBean getLoginBean() {
        return loginBean;
    }

    public void setLoginBean(LoginBean loginBean) {
        this.loginBean = loginBean;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Category getCategory() {
        return category = navi.getCategory();
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    public QuestionService getQuestionService() {
        return questionService;
    }

    public void setQuestionService(QuestionService questionService) {
        this.questionService = questionService;
    }

    public boolean isRightAnswersShouldBeShown() {
        return rightAnswersShouldBeShown;
    }

    public void setRightAnswersShouldBeShown(boolean rightAnswersShouldBeShown) {
        this.rightAnswersShouldBeShown = rightAnswersShouldBeShown;
    }

    public Question getQuestion() {
        int quType;
        if (this.kindOfTest == 1) {
            questionsPerCat = getQuestionsOfCategoryPerTestStep().size();
            question = getQuestionsOfCategoryPerTestStep().get(questionCnt);

        }
        if (kindOfTest == 2) {
            question = qList.get(questionCnt);

        }

        quType = question.getQuestionTypeID();
        isMultCh = false;
        isText = false;
        isComparison = false;
        isNumbering = false;
        isPicSelection = false;
        isVideo = false;
        isSolutionRequired = false;
        rightAnswersShouldBeShown = true;
        columnCnt = 0;
        if (question.getId() == 19) {
            columnCnt = 5;
        }
        if (quType == 2) {
            isMultCh = true;
        }
        if (quType == 1) {
            this.isText = true;
        }
        if (quType == 3) {
            this.isComparison = true;
            this.rightAnswersShouldBeShown=false;
            if(cnt==2){
                this.isSolutionRequired=true;
            }
        }
        if (quType == 4) {
            this.isNumbering = true;
        }
        if (quType == 5) {
            this.isPicSelection = true;
        }
        if (quType == 6) {
            this.isVideo = true;
        }

        return question;
    }

    public void setQuestion(Question question) {
        this.question = question;
    }

    public List<Answer> getAnswers() {
        answerList = answerService.getAnswersPerQuestion(question.getId());
        if (answerList.size() > 0) {
            if (answerList.get(0).getFbNR() != 0) {
                columnCnt = 1;
            }
        }
        return answerList;
    }

    public Map<Integer, String> getInputMap() {
        return inputMap;
    }

    public boolean isIsMultCh() {
        return isMultCh;
    }

    public void setIsMultCh(boolean isMultCh) {
        this.isMultCh = isMultCh;
    }

    public boolean isIsVideo() {
        return isVideo;
    }

    public void setIsVideo(boolean isVideo) {
        this.isVideo = isVideo;
    }

    public boolean isIsText() {
        return isText;
    }

    public void setIsText(boolean isText) {
        this.isText = isText;
    }

    public boolean isIsComparison() {
        return isComparison;
    }

    public void setIsComparison(boolean isComparison) {
        this.isComparison = isComparison;
    }

    public void saveNavigation() {
        navi.addNavigationComponent("Kategorie auswählen");
    }

    public boolean isIsNumbering() {
        return isNumbering;
    }

    public void setIsNumbering(boolean isNumbering) {
        this.isNumbering = isNumbering;
    }

    public boolean isIsSolutionRequired() {
        return isSolutionRequired;
    }

    public void setIsSolutionRequired(boolean isSolutionRequired) {
        this.isSolutionRequired = isSolutionRequired;
    }

    public void next(ActionEvent e) {
        action = "/questions.xhtml";
        if (cnt == 1) {
            boolean isCorrect = true;
            if (questionCnt < questionsPerCat) {
                if (isMultCh) {
                    boolMap.remove("get");
                    for (Answer a : answerList) {
                        if (a.getCorrect()) {
                            a.setBackcolor("background:#04B404;");
                            a.setTextcolor("color:white;");
                        } else {
                            a.setBackcolor("background:#C60606;");
                            a.setTextcolor("color:white;");
                        }
                        if (!a.getCorrect() == boolMap.get(a.getId())) {
                            isCorrect = false;
                        }
                    }
                }
                if (isText) {
                    boolean fbDependent = false;
                    int fbNumUser = loginBean.getLs().getFirebrigade().getFirebrigadenumber();
                    int fbNumAns = 0;
                    inputMap.remove("get");
                    List<String> ansInputTextList = new ArrayList<>(inputMap.values());
                    for (Answer a : answerList) {
                        selectedAnswers.add(a.getText()); //Liste der richtigen Antworten aus der Datenbank in Form von List<String>
                        if ((fbNumAns = a.getFbNR()) != 0) {
                            fbDependent = true;
                            break;
                        }
                    }
                    if (fbDependent) {
                        String corrAnswer = "";
                        if (fbNumAns == 11) {
                            String ansText = answerList.get(0).getText();
                            if (ansText.equals(this.COMMANDER)) {
                                corrAnswer = loginBean.getLs().getFirebrigade().getCommander();
                            }
                            if (ansText.equals(this.YOUTHCOMMANDER)) {
                                corrAnswer = loginBean.getLs().getFirebrigade().getYouthCommander();
                            }
                            if (ansText.equals(this.FOUNDINGYEAR)) {
                                corrAnswer = loginBean.getLs().getFirebrigade().getFoundingYear();
                            }

src/main/java/Beans/TestBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Beans;

import POJO.Test;
import Properties.PathProperties;
import Services.TestService;
import java.io.Serializable;
import javax.faces.event.ActionEvent;
/**
 *
 * @author Lisa
 */

public class TestBean implements Serializable{

    private NavigationBean navi;
    private TestService testservice = TestService.getInstance();
    private PathProperties prop=PathProperties.getInstance();
    
    public void home(ActionEvent event) {
        navi.setTest(null);
    }

    public NavigationBean getNavi() {
        return navi;
    }

    public void setNavi(NavigationBean navi) {
        this.navi = navi;
    }

    public TestService getTestservice() {
        return testservice;
    }

    public void setTestservice(TestService testservice) {
        this.testservice = testservice;
    }

    public void saveNavigation(Test test) {
        navi.setTest(test);
        navi.addNavigationComponent("Teststufe auswählen");
    }
    
    public String changePersonalData(){
        String navigateTo=null;
        return navigateTo;
    }
}

src/main/webapp/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pm="http://primefaces.org/mobile">
    <h:head>
        <title>Onlinetrainer</title>   
    </h:head>
    <h:body>
        <script>
            history.pushState(null, document.title, location.href);
            window.addEventListener('popstate', function(event)
            {
                history.pushState(null, document.title, location.href);
            });
        </script> 
        <script>
            window.onbeforeunload = confirmExit;
            function confirmExit()
            {
                myCommand();
            }
        </script>
        <f:view transient="true">
            <h:form onkeypress="if (event.keyCode === 13) {
                        return false;
                    }"> 
                <h:outputStylesheet library="css" name="styles.css"/>
                <h:outputScript library="primefaces" name="hotkey/hotkey.js" target="head"></h:outputScript>
                <pm:page id="pageid">
                    <p:graphicImage library="images" name="logo_onlinetrainer.png" width="100%" height="auto"/>
                    <p:panelGrid columns="2" layout="grid">
                        <p:outputLabel value="Home" class="heading"/>
                        <p:panelGrid columns="1" style="float: right">
                            <p:commandButton value="Logout" style="width:auto" styleClass="mybutton" action="#{questionBean.logout}"/>
                            <p:commandButton styleClass="mybutton" value="?" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop);">
                                <p:fileDownload value="#{fileDownloadBean.helpFile}" />
                            </p:commandButton>
                        </p:panelGrid>  
                        <p:outputLabel value=""/>
                        <p:commandButton styleClass="mybutton" style="width:auto; float: right" value="Administratorhandbuch" ajax="false" rendered="#{loginBean.ls.isAdmin}" onclick="PrimeFaces.monitorDownload(start, stop);">
                            <p:fileDownload value="#{fileDownloadBean.adminHelp}" />
                        </p:commandButton>
                        <p:commandButton styleClass="mybutton" style="width:auto; float: right" value="Superuserhandbuch" ajax="false" rendered="#{loginBean.ls.isSuperUser}" onclick="PrimeFaces.monitorDownload(start, stop);">
                            <p:fileDownload value="#{fileDownloadBean.superuserHelp}" />
                        </p:commandButton> 
                    </p:panelGrid>
                    <area onclick="confirmExit();"/>
                    <p:remoteCommand name="myCommand" action="#{questionBean.logoutOnBrowserCloseEvent}"/>
                    <pm:content>
                        <p:panelGrid columns="1" id="panelGridid">
                            <p:row>
                                <p:outputLabel value="Hallo #{loginBean.ls.nameOfUser}" class="text"/>
                            </p:row> 
                            <p:commandButton id="btn1" value="Übungsprogramm starten" class="mybutton" actionListener="#{navigationBean.saveTestNavigation}"
                                             action="/chooseTest.xhtml" widgetVar="ueben"/>
                            <p:commandButton value="Persönliche Daten ändern" styleClass="mybutton" action="/changePersonalData.xhtml" rendered="#{loginBean.ls.isAdminOrSuperUser}"/>
                            <p:commandButton value="Feuerwehrdaten ändern" styleClass="mybutton" action="/changeFirebrigadeData.xhtml" rendered="#{loginBean.ls.isSuperUser}"/>
                            <p:commandButton value="Benutzerverwaltung" styleClass="mybutton" action="/usermanagement.xhtml" rendered="#{loginBean.ls.isAdmin}"/>
                            <p:panelGrid columns="2" rendered="#{loginBean.ls.isAdmin}">
                                <p:commandButton value="Statistik" styleClass="mybutton" action="/statisticsAdmin.xhtml"/>
                                <p:selectOneMenu value="#{chartView.year}">
                                    <f:selectItems var="year" value="#{chartView.yearList}" itemValue="#{year}"/>
                                </p:selectOneMenu> 
                            </p:panelGrid>
                            <p:panelGrid columns="2" rendered="#{loginBean.ls.isSuperUser}">
                                <p:commandButton value="Statistik" styleClass="mybutton" action="/statisticsSuperuser.xhtml"/>
                                <p:selectOneMenu value="#{chartView.year}">
                                    <f:selectItems var="year" value="#{chartView.yearList}" itemValue="#{year}"/>
                                </p:selectOneMenu> 
                            </p:panelGrid>
                            <p:commandButton value="Daten verwalten" styleClass="mybutton" action="/editdata.xhtml" rendered="#{loginBean.ls.isAdmin}"/>
                        </p:panelGrid> 
                        <p:defaultCommand target="btn1"/>
                    </pm:content>
                </pm:page>
            </h:form>
        </f:view>
    </h:body>
</html>

src/main/webapp/questions.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pm="http://primefaces.org/mobile">    
    <h:head>
        <title>Onlinetrainer</title>
    </h:head>
    <h:body>
        <script>
            history.pushState(null, document.title, location.href);
            window.addEventListener('popstate', function (event)
            {
                history.pushState(null, document.title, location.href);
            });
        </script>
        <f:view id="view" transient="true">
            <h:outputStylesheet library="css" name="styles.css"/>
            <h:form onkeypress="if (event.keyCode === 13) {
                        return false;
                    }">
                <pm:page>
                    <pm:content>
                        <p:graphicImage library="images" name="logo_onlinetrainer.png" width="100%" height="auto"/>
                        <h:outputStylesheet library="css" name="styles.css"/>
                        <p:panelGrid columns="2">
                            <p:outputLabel value="#{questionBean.navi.testStep.name} #{questionBean.categoryNameWithArrow}" styleClass="heading"/>
                            <h:panelGrid columns="2" style="float: right" >
                                <p:commandButton value="Home" styleClass="mybutton" style="width:auto;" action="/home.xhtml" actionListener="#{questionBean.home}"/>
                                <p:commandButton styleClass="mybutton" value="?" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop);">
                                    <p:fileDownload value="#{fileDownloadBean.helpFile}" />
                                </p:commandButton>
                            </h:panelGrid>    
                        </p:panelGrid>  
                        <p:panelGrid columns="1">
                            <h:outputText value="#{questionBean.question.text}" styleClass="text"/>
                            <h:outputText value="#{questionBean.hint}" styleClass="text" style="font-weight: bold"/>
                            <h:dataTable id="d" rows="#{questionBean.columnCnt}" var="answer" value="#{questionBean.answers}" rendered="#{questionBean.isText}" styleClass="datatable">
                                <h:column>
                                    <h:inputText value="#{questionBean.inputMap.get(answer.id)}"  valueChangeListener="#{questionBean.valueChanged}"
                                                 styleClass="input" style="#{answer.textcolor}" autocomplete="off">
                                        <p:ajax update="d"/>
                                        <f:attribute name="answer" value="#{answer}"/>
                                    </h:inputText>
                                </h:column>
                            </h:dataTable>

                            <h:dataTable var="answer" value="#{questionBean.answers}" rendered="#{questionBean.isNumbering}" styleClass="datatable">
                                <h:column>
                                    <h:inputText id="numberInput" value="#{questionBean.numMap.get(answer.id)}"  valueChangeListener="#{questionBean.valueChangedNumber}"
                                                 style="#{answer.textcolor};width:35px" autocomplete="off">
                                        <p:ajax update="numberInput"/>
                                        <f:attribute name="answer" value="#{answer}"/>
                                        <f:converter converterId="NumberConverterID"/>
                                    </h:inputText>
                                </h:column>
                                <h:column>
                                    <h:outputText value="#{answer.text}" styleClass="text"/>
                                </h:column>
                            </h:dataTable>
                            <h:messages for="numberInput"/>
                            <h:dataTable var="ans" value="#{questionBean.answers}" cellspacing="1" rendered="#{questionBean.isMultCh}" >
                                <h:column>
                                    <p:selectBooleanCheckbox value="#{questionBean.boolMap.get(ans.id)}"  valueChangeListener="#{questionBean.valueChangedMult}"
                                                             style="width:25px" styleClass="input">
                                        <f:attribute name="ans" value="#{ans}"/>
                                    </p:selectBooleanCheckbox>
                                </h:column>
                                <h:column> 
                                    <p:outputLabel value="#{ans.text}" style="#{ans.backcolor}#{ans.textcolor}"/>
                                </h:column>
                            </h:dataTable>

                            <h:dataTable var="ans" value="#{questionBean.answers}" cellspacing="2" rendered="#{questionBean.isPicSelection}" >
                                <h:column>
                                    <p:panelGrid columns="1">
                                        <p:selectBooleanCheckbox value="#{questionBean.boolMap.get(ans.id)}"  valueChangeListener="#{questionBean.valueChangedMult}"
                                                                 styleClass="input" style="width:25px">
                                            <!--<f:ajax execute="@this" render="@this"/>-->
                                            <f:attribute name="ans" value="#{ans}"/>
                                        </p:selectBooleanCheckbox>
                                        <p:graphicImage library="images" name="#{ans.text}" width="auto" height="130" />
                                    </p:panelGrid>
                                </h:column>
                                <h:column>
                                    <h:outputText value="#{ans.picSelectionText}" style="#{ans.picSelectionColor}"/>
                                </h:column>
                            </h:dataTable>

                            <!--<p:commandButton value="Lösung anzeigen" actionListener="{questionBean.showSolution}" styleClass="button" rendered="{questionBean.isComparison}">
                                <f:ajax execute="@this" render="image1"/>
                            </p:commandButton>-->
                            <h:dataTable id="image1" var="ans" value="#{questionBean.answers}" cellspacing="2" rendered="#{questionBean.isComparison}" >
                                <h:column>
                                    <h:graphicImage library="images" name="#{ans.text}" width="auto" height="130" rendered="#{questionBean.isSolutionRequired}"/> 
                                </h:column>
                            </h:dataTable>

                            <h:dataTable var="ans" value="#{questionBean.answers}" cellspacing="2" rendered="#{questionBean.isVideo}" >
                                <h:column>
                                    <h:outputLink id="link1" value="#{ans.text}" target="_blank">
                                        <h:outputText class="button" value="Lösung anzeigen"/>
                                    </h:outputLink>
                                </h:column>
                            </h:dataTable>

                        </p:panelGrid>
                        <h:commandButton id="next" value="Weiter" actionListener="#{questionBean.next}" action="#{questionBean.action()}" styleClass="mybutton"/>
                    </pm:content>
                    <h:outputText value="#{questionBean.correct}" rendered="#{questionBean.rightAnswersShouldBeShown}" styleClass="text"/>
                </pm:page>
            </h:form>
        </f:view>
    </h:body>
</html>